import tkinter

root = tkinter.Tk()
title = tkinter.Label(root, text="Kalkulator")
operation = tkinter.Label(root, text="")
bt_0 = tkinter.Button(root, text="0")
bt_1 = tkinter.Button(root, text="1")
bt_2 = tkinter.Button(root, text="2")
bt_3 = tkinter.Button(root, text="3")
bt_4 = tkinter.Button(root, text="4")
bt_5 = tkinter.Button(root, text="5")
bt_6 = tkinter.Button(root, text="6")
bt_7 = tkinter.Button(root, text="7")
bt_8 = tkinter.Button(root, text="8")
bt_9 = tkinter.Button(root, text="9")
bt_sum = tkinter.Button(root, text="+")
bt_sub = tkinter.Button(root, text="-")
bt_mul = tkinter.Button(root, text="*")
bt_div = tkinter.Button(root, text=chr(247))
bt_result = tkinter.Button(root, text='=')
bt_delete = tkinter.Button(root, text="DEL")
bt_bracketL = tkinter.Button(root, text="(")
bt_bracketR = tkinter.Button(root, text=")")
title.pack()
operation.pack()
bt_0.pack()
bt_1.pack()
bt_2.pack()
bt_3.pack()
bt_4.pack()
bt_5.pack()
bt_6.pack()
bt_7.pack()
bt_8.pack()
bt_9.pack()
bt_sum.pack()
bt_sub.pack()
bt_mul.pack()
bt_div.pack()
bt_result.pack()
bt_delete.pack()
bt_bracketL.pack()
bt_bracketR.pack()


root.mainloop()
